name             'drone-chef-upload-test1'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures drone-chef-upload-test1'
long_description 'Installs/Configures drone-chef-upload-test1'
version          '0.1.0'
